[package]
name = "legio-parser"
description = "Parsing library that uses combinatory logic."
license = "APACHE"
license-file = "LICENSE"
version = "0.1.0"
authors = ["Kiril Mihaylov <Kiril195@hotmail.com>"]
edition = "2018"

[features]
default = ["std"]

std = []

[dependencies]
