name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo +nightly build --verbose
    - name: Build without "std"
      run: cargo +nightly build --no-default-features --verbose
    - name: Run tests
      run: cargo +nightly test --verbose
    - name: Run tests without "std"
      run: cargo +nightly test --no-default-features --verbose
