name: Rust

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --features "no_track_caller" --verbose

  build_no_std:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build without "std"
      run: cargo build --no-default-features --features "no_track_caller" --verbose

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --features "no_track_caller" --verbose

  test_no_std:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests without "std"
      run: cargo test --no-default-features --features "no_track_caller" --verbose
